POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Example blog",
  "author": "Kim",
  "url": "https://www.exampleblog.com",
  "likes": 2
}

###
GET http://localhost:3003/api/blogs