GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/2

###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Kim Dinh",
  "number": "111-111-1111"
}

